// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileManager is an autogenerated mock type for the FileManager type
type FileManager struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: dirPath
func (_m *FileManager) CreateDirectory(dirPath string) error {
	ret := _m.Called(dirPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dirPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: itemPath
func (_m *FileManager) Exists(itemPath string) (bool, error) {
	ret := _m.Called(itemPath)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(itemPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(itemPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTempDirectory provides a mock function with given fields:
func (_m *FileManager) GetTempDirectory() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Zip provides a mock function with given fields: zipFilePath, files
func (_m *FileManager) Zip(zipFilePath string, files []string) error {
	ret := _m.Called(zipFilePath, files)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(zipFilePath, files)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
