version: "3.9"
services:
  mongo_server:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb_data:/data/db
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongo_express:
    image: mongo-express
    depends_on:
      mongo_server:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_SERVER: "mongo_server"




