// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/pjover/sam/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ConfigService is an autogenerated mock type for the ConfigService type
type ConfigService struct {
	mock.Mock
}

// GetCurrentYearMonth provides a mock function with given fields:
func (_m *ConfigService) GetCurrentYearMonth() model.YearMonth {
	ret := _m.Called()

	var r0 model.YearMonth
	if rf, ok := ret.Get(0).(func() model.YearMonth); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.YearMonth)
	}

	return r0
}

// GetCustomersCardsDirectory provides a mock function with given fields:
func (_m *ConfigService) GetCustomersCardsDirectory() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvoicesDirectory provides a mock function with given fields:
func (_m *ConfigService) GetInvoicesDirectory() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportsDirectory provides a mock function with given fields:
func (_m *ConfigService) GetReportsDirectory() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetString provides a mock function with given fields: key
func (_m *ConfigService) GetString(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTime provides a mock function with given fields: key
func (_m *ConfigService) GetTime(key string) time.Time {
	ret := _m.Called(key)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetWorkingDirectory provides a mock function with given fields:
func (_m *ConfigService) GetWorkingDirectory() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ConfigService) Init() {
	_m.Called()
}

// SetCurrentYearMonth provides a mock function with given fields: yearMonth
func (_m *ConfigService) SetCurrentYearMonth(yearMonth model.YearMonth) error {
	ret := _m.Called(yearMonth)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.YearMonth) error); ok {
		r0 = rf(yearMonth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetString provides a mock function with given fields: key, value
func (_m *ConfigService) SetString(key string, value string) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTime provides a mock function with given fields: key, value
func (_m *ConfigService) SetTime(key string, value time.Time) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Time) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
